/// Cambodia's 25 provinces/cities (Phnom Penh first, then alphabetical),
/// and Phnom Penh's 14 khans (districts) each mapped to their sangkats
/// (communes), per the current administrative structure.
const List<String> kCambodiaProvinces = [
  'Phnom Penh',
  'Banteay Meanchey',
  'Battambang',
  'Kampong Cham',
  'Kampong Chhnang',
  'Kampong Speu',
  'Kampong Thom',
  'Kampot',
  'Kandal',
  'Kep',
  'Koh Kong',
  'Kratie',
  'Mondulkiri',
  'Oddar Meanchey',
  'Pailin',
  'Preah Sihanouk',
  'Preah Vihear',
  'Prey Veng',
  'Pursat',
  'Ratanakiri',
  'Siem Reap',
  'Stung Treng',
  'Svay Rieng',
  'Takeo',
  'Tboung Khmum',
];

const Map<String, List<String>> kPhnomPenhDistricts = {
  'Chamkar Mon': [
    'Tonle Basak',
    'Tuol Tumpung I',
    'Tuol Tumpung II',
    'Boeng Trabaek',
    'Phsar Daeum Thkov',
  ],
  'Doun Penh': [
    'Srah Chak',
    'Wat Phnom',
    'Phsar Chas',
    'Phsar Kandal I',
    'Phsar Kandal II',
    'Chey Chumneas',
    'Chaktomuk',
    'Phsar Thmey I',
    'Phsar Thmey II',
    'Phsar Thmey III',
    'Boeng Reang',
  ],
  'Prampir Makara': [
    'Monorom',
    'Mittapheap',
    'Veal Vong',
    'Orussey I',
    'Orussey II',
    'Orussey III',
    'Orussey IV',
    'Boeung Prolit',
  ],
  'Tuol Kork': [
    'Boeng Kak I',
    'Boeng Kak II',
    'Phsar Depo I',
    'Phsar Depo II',
    'Phsar Depo III',
    "Tuek L'ak I",
    "Tuek L'ak II",
    "Tuek L'ak III",
    'Phsar Daeumkor',
    'Boeng Salang',
  ],
  'Dangkao': [
    'Dangkao',
    'Pong Tuek',
    'Prey Veaeng',
    'Prey Sa',
    'Krang Pongro',
    'Sak Sampov',
    'Cheung Aek',
    'Kong Noy',
    'Preaek Kampues',
    'Roluos',
    'Spean Thma',
    'Tien',
  ],
  'Mean Chey': [
    'Chak Angrae Leu',
    'Chak Angrae Kraom',
    'Stueng Mean Chey I',
    'Stueng Mean Chey II',
    'Stueng Mean Chey III',
    'Boeng Tumpun I',
    'Boeng Tumpun II',
  ],
  'Russey Keo': [
    'Svay Pak',
    'Kilomet Prammouy',
    'Russey Keo',
    'Chrang Chamreh I',
    'Chrang Chamreh II',
    'Tuol Sangkae I',
    'Tuol Sangkae II',
  ],
  'Sen Sok': [
    'Phnom Penh Thmei',
    'Tuek Thla',
    'Khmuonh',
    'Krang Thnong',
    "Ou Baek K'am",
    'Kouk Khleang',
  ],
  'Pou Senchey': [
    'Trapeang Krasang',
    'Samraong Kraom',
    'Chaom Chau I',
    'Chaom Chau II',
    'Chaom Chau III',
    'Kakab I',
    'Kakab II',
  ],
  'Chroy Changvar': [
    'Prek Leap',
    'Prek Ta Sek',
    'Chroy Changvar',
    'Bak Khaeng',
    'Koh Dach',
  ],
  'Prek Pnov': ['Ponhea Pon', 'Prek Pnov', 'Samraong', 'Kouk Roka', 'Ponsang'],
  'Chbar Ampov': [
    'Chbar Ampov I',
    'Chbar Ampov II',
    'Nirouth',
    'Prek Pra',
    'Veal Sbov',
    'Prek Aeng',
    'Kbal Koh',
    'Prek Thmei',
  ],
  'Boeng Keng Kang': [
    'Boeng Keng Kang I',
    'Boeng Keng Kang II',
    'Boeng Keng Kang III',
    'Olympic',
    'Tumnob Tuek',
    'Tuol Svay Prey I',
    'Tuol Svay Prey II',
  ],
  'Kamboul': [
    'Kamboul',
    'Kantouk',
    'Ovlaok',
    'Snaor',
    'Phleung Chheh Roteh',
    'Boeng Thum',
    'Prateah Lang',
  ],
};

/// All 105 Phnom Penh sangkats across every khan, alphabetized, for pickers
/// that let the sangkat be chosen independently of the khan field.
final List<String> kPhnomPenhSangkats =
    kPhnomPenhDistricts.values.expand((sangkats) => sangkats).toList()..sort();

/// Districts and communes (sangkats) for every province, keyed by the
/// province name exactly as it appears in [kCambodiaProvinces], sourced
/// from Cambodia's commune-level administrative gazetteer. Phnom Penh
/// reuses the curated [kPhnomPenhDistricts] (post-2020 khan split).
const Map<String, Map<String, List<String>>> kCambodiaDistricts = {
  'Phnom Penh': kPhnomPenhDistricts,
  'Banteay Meanchey': {
    'Mongkol Borei': [
      'Banteay Neang',
      'Bat Trang',
      'Chamnaom',
      'Kouk Ballangk',
      'Koy Maeng',
      'Ou Prasat',
      'Phnum Touch',
      'Rohat Tuek',
      'Ruessei Kraok',
      'Sambuor',
      'Soea',
      'Srah Reang',
      'Ta Lam',
    ],
    'Phnum Srok': [
      'Nam Tau',
      'Poy Char',
      'Ponley',
      'Spean Sraeng',
      'Srah Chik',
      'Phnum Dei',
    ],
    'Preah Netr Preah': [
      'Chnuor Mean Chey',
      'Chob Vari',
      'Phnum Lieb',
      'Prasat',
      'Preak Netr Preah',
      'Rohal',
      'Tean Kam',
      'Tuek Chour',
      'Bos Sbov',
    ],
    'Ou Chrov': [
      'Changha',
      'Koub',
      'Kuttasat',
      'Samraong',
      'Souphi',
      'Soengh',
      'Ou Beichoan',
    ],
    'Serei Saophoan Municipality': [
      'Kampong Svay Sangkat',
      'Kaoh Pong Satv Sangkat',
      'Mkak Sangkat',
      'Ou Ambel Sangkat',
      'Phniet Sangkat',
      'Preah Ponlea Sangkat',
      'Tuek Thla Sangkat',
    ],
    'Thma Puok': [
      'Banteay Chhmar',
      'Kouk Romiet',
      'Phum Thmei',
      'Thma Puok',
      'Kouk Kakthen',
      'Kumru',
    ],
    'Svay Chek': [
      'Phkoam',
      'Sarongk',
      'Sla Kram',
      'Svay Chek',
      'Ta Baen',
      'Ta Phou',
      'Treas',
      'Roluos',
    ],
    'Malai': [
      'Boeng Beng',
      'Malai',
      'Ou Sampoar',
      'Ou Sralau',
      'Tuol Pongro',
      'Ta Kong',
    ],
    'Paoy Paet Municipality': [
      'Nimitt Sangkat',
      'Paoy Paet Sangkat',
      'Phsar Kandal Sangkat',
    ],
  },
  'Battambang': {
    'Banan': [
      'Kantueu Muoy',
      'Kantueu Pir',
      'Bay Damram',
      'Chheu Teal',
      'Chaeng Mean Chey',
      'Phnum Sampov',
      'Snoeng',
      'Ta Kream',
    ],
    'Thma Koul': [
      'Ta Pung',
      'Ta Meun',
      'Ou Ta Ki',
      'Chrey',
      'Anlong Run',
      'Chrouy Sdau',
      'Boeng Pring',
      'Kouk Khmum',
      'Bansay Traeng',
      'Rung Chrey',
    ],
    'Battambang Municipality': [
      'Tuol Ta Ek Sangkat',
      'Prek Preah Sdach Sangkat',
      'Rottanak Sangkat',
      'Chomkar Somraong Sangkat',
      'Sla Ket Sangkat',
      'Kdol Doun Teav Sangkat',
      'OMal Sangkat',
      'wat Kor Sangkat',
      'Ou Char Sangkat',
      'Svay Por Sangkat',
    ],
    'Bavel': [
      'Bavel',
      'Khnach Romeas',
      'Lvea',
      'Prey Khpos',
      'Ampil Pram Daeum',
      'Kdol Ta Haen',
      'Khlaeng Meas',
      'Boeung Pram',
    ],
    'Aek Phnum': [
      'Preaek Norint',
      'Samraong Knong',
      'Preaek Khpob',
      'Preaek Luong',
      'Peam Aek',
      'Prey Chas',
      'Kaoh Chiveang',
    ],
    'Moung Ruessei': [
      'Moung',
      'Kear',
      'Prey Svay',
      'Ruessei Krang',
      'Chrey',
      'Ta Loas',
      'Kakaoh',
      'Prey Touch',
      'Robas Mongkol',
    ],
    'Rotonak Mondol': [
      'Sdau',
      'Andaeuk Haeb',
      'Phlov Meas',
      'Traeng',
      'Reaksmei Songha',
    ],
    'Sangkae': [
      'Anlong Vil',
      'Norea',
      'Ta Pon',
      'Roka',
      'Kampong Preah',
      'Kampong Prieng',
      'Reang Kesei',
      'Ou Dambang Muoy',
      'Ou Dambang Pir',
      'Vaot Ta Muem',
    ],
    'Samlout': [
      'Ta Taok',
      'Kampong Lpov',
      'Ou Samril',
      'Sung',
      'Samlout',
      'Mean Chey',
      'Ta Sanh',
    ],
    'Sampov Lun': [
      'Sampov Lun',
      'Angkor Ban',
      'Ta Sda',
      'Santepheap',
      'Serei Mean Chey',
      'Chrey Seima',
    ],
    'Phnum Proek': [
      'Phnum Proek',
      'Pech Chenda',
      'Bour',
      'Barang Thleak',
      'Ou Rumduol',
    ],
    'Kamrieng': [
      'Kamrieng',
      'Boeng Reang',
      'Ou Da',
      'Trang',
      'Ta Saen',
      'Ta Krei',
    ],
    'Koas Krala': [
      'Thipakdei',
      'Kaos Krala',
      'Hab',
      'Preah Phos',
      'Doun Ba',
      'Chhnal Moan',
    ],
    'Rukh Kiri': [
      'Preaek Chik',
      'Prey Tralach',
      'Mukh Reah',
      'Sdok Pravoek',
      'Basak',
    ],
  },
  'Kampong Cham': {
    'Batheay': [
      'Batheay',
      'Chbar Ampov',
      'Chealea',
      'Cheung Prey',
      'Me Pring',
      "Ph'av",
      'Sambour',
      'Sandaek',
      'Tang Krang',
      'Tang Krasang',
      'Trab',
      'Tumnob',
    ],
    'Chamkar Leu': [
      'Bos Khnor',
      'Chamkar Andoung',
      'Cheyyou',
      'Lvea Leu',
      'Spueu',
      'Svay Teab',
      'Ta Ong',
      'Ta Prok',
    ],
    'Cheung Prey': [
      'Khnor Dambang',
      'Kouk Rovieng',
      'Pdau Chum',
      'Prey Char',
      'Pring Chrum',
      'Sampong Chey',
      'Sdaeung Chey',
      'Soutib',
      'Sramar',
      'Trapeang Kor',
    ],
    'Kampong Cham Municipality': [
      'Boeng Kok Sangkat',
      'Kampong Cham Sangkat',
      'Sambuor Meas Sangkat',
      'Veal Vong Sangkat',
    ],
    'Kampong Siem': [
      'Ampil',
      'Hanchey',
      'Kien Chrey',
      'Kokor',
      'Kaoh Mitt',
      'Kaoh Roka',
      'Kaoh Samraong',
      'Kaoh Tontuem',
      'Krala',
      'Ou Svay',
      "Ro'ang",
      'Rumchek',
      'Srak',
      'Trean',
      'Vihear Thum',
    ],
    'Kang Meas': [
      'Angkor Ban',
      'Kang Ta Noeng',
      'Khchau',
      'Peam Chi Kang',
      'Preaek Koy',
      'Preaek Krabau',
      'Reay Pay',
      'Roka Ar',
      'Roka Koy',
      'Sdau',
      'Sour Kong',
    ],
    'Kaoh Soutin': [
      'Kampong Reab',
      'Kaoh Sotin',
      'Lve',
      'Moha Leaph',
      'Moha Khnhoung',
      'Peam Prathnuoh',
      'Pongro',
      'Preaek Ta Nong',
    ],
    'Prey Chhor': [
      'Baray',
      'Boeng Nay',
      'Chrey Vien',
      'Khvet Thum',
      'Kor',
      'Krouch',
      'Lvea',
      'Mien',
      'Prey Chhor',
      'Sour Saen',
      'Samraong',
      'Sragnae',
      'Thma Pun',
      'Tong Rong',
      'Trapeang Preah',
    ],
    'Srei Santhor': [
      'Baray',
      'Chi Bal',
      'Khnar Sa',
      'Kaoh Andaet',
      'Mean Chey',
      'Phteah Kandal',
      'Pram Yam',
      'Preaek Dambouk',
      'Preaek Pou',
      'Preaek Rumdeng',
      'Ruessei Srok',
      'Svay Pou',
      'Svay Khsach Phnum',
      'Tong Tralach',
    ],
    'Stueng Trang': [
      'Areaks Tnot',
      'Dang Kdar',
      'Khpob Ta Nguon',
      'Me Sar Chrey',
      'Ou Mlu',
      'Peam Kaoh Snar',
      'Preah Andoung',
      'Preaek Bak',
      'Preak Kak',
      'Soupheas',
      'Tuol Preah Khleang',
      'Tuol Sambuor',
    ],
  },
  'Kampong Chhnang': {
    'Baribour': [
      'Anhchanh Rung',
      'Chhnok Tru',
      'Chak',
      'Khon Rang',
      'Kampong Preah Kokir',
      'Melum',
      'Phsar',
      'Pech Changvar',
      'Popel',
      'Ponley',
      'Trapeang Chan',
    ],
    'Chol Kiri': [
      'Chol Sar',
      'Kaoh Thkov',
      'Kampong Ous',
      'Peam Chhkaok',
      'Prey Kri',
    ],
    'Kampong Chhnang Municipality': [
      'Phsar Chhnang Sangkat',
      'Kampong Chhnang Sangkat',
      "B'er Sangkat",
      'Khsam Sangkat',
    ],
    'Kampong Leaeng': [
      'Chranouk',
      'Dar',
      'Kampong Hau',
      'Phlov Tuk',
      'Pou',
      'Pralay Meas',
      'Samraong Saen',
      'Svay Rumpear',
      'Trangel',
    ],
    'Kampong Tralach': [
      'Ampil Tuek',
      'Chhuk Sa',
      'Chres',
      'Kampong Tralach',
      'Longveaek',
      'Ou Ruessei',
      'Peani',
      'Saeb',
      'Ta Ches',
      'Thma Edth',
    ],
    "Rolea B'ier": [
      'Andoung Snay',
      'Banteay Preal',
      'Cheung Kreav',
      'Chrey Bak',
      'Kouk Banteay',
      'Krang Leav',
      'Pongro',
      'Prasnoeb',
      'Prey Mul',
      "Rolea B'ier",
      'Srae Thmei',
      'Svay Chrum',
      'Tuek Hout',
    ],
    'Sameakki Mean Chey': [
      'Chhean Laeung',
      'Khnar Chhmar',
      'Krang Lvea',
      'Peam',
      'Sedthei',
      'Svay',
      'Svay Chuk',
      'Tbaeng Khpos',
      'Thlok Vien',
    ],
    'Tuek Phos': [
      'Akphivoadth',
      'Chieb',
      'Chaong Maong',
      'Kbal Tuek',
      'Khlong Popok',
      'Krang Skear',
      'Tang Krasang',
      'Tuol Khpos',
      'Kdol Saen Chey',
    ],
  },
  'Kampong Speu': {
    'Basedth': [
      'Basedth',
      'Kat Phluk',
      'Nitean',
      'Pheakdei',
      'Pheari Mean Chey',
      'Phong',
      'Pou Angkrang',
      'Pou Chamraeun',
      'Pou Mreal',
      'Svay Chacheb',
      'Tuol Ampil',
      'Tuol Sala',
      'Kak',
      'Svay Rumpear',
      'Preah Khae',
    ],
    'Chbar Mon Municipality': [
      'Chbar Mon Sangkat',
      'Kandaol Dom Sangkat',
      'Rokar Thum Sangkat',
      'Sopoar Tep Sangkat',
      'Svay Kravan Sangkat',
    ],
    'Kong Pisei': [
      'Angk Popel',
      'Chongruk',
      'Moha Ruessei',
      'Pechr Muni',
      'Preah Nipean',
      'Prey Nheat',
      'Prey Vihear',
      'Roka Kaoh',
      'Sdok',
      'Snam Krapeu',
      'Srang',
      "Tuek L'ak",
      'Veal',
    ],
    'Aoral': [
      'Haong Samnam',
      'Reaksmei Sameakki',
      'Trapeang Chour',
      'Sangkae Satob',
      'Ta Sal',
    ],
    'Odongk': [
      'Chan Saen',
      'Cheung Roas',
      'Chumpu Proeks',
      'Khsem Khsant',
      'Krang Chek',
      'Mean Chey',
      'Preah Srae',
      'Prey Krasang',
      'Trach Tong',
      'Veal Pong',
      'Veang Chas',
      'Yutth Sameakki',
      'Damnak Reang',
      'Peang Lvea',
      'Phnom Touch',
    ],
    'Phnum Sruoch': [
      'Chambak',
      'Choam Sangkae',
      'Dambouk Rung',
      'Kiri Voan',
      'Krang Dei Vay',
      'Moha Sang',
      'Ou',
      'Prey Rumduol',
      'Prey Kmeng',
      'Tang Samraong',
      'Tang Sya',
      'Traeng Trayueng',
    ],
    'Samraong Tong': [
      'Roleang Chak',
      'Kahaeng',
      'Khtum Krang',
      'Krang Ampil',
      'Pneay',
      'Roleang Kreul',
      'Samrong Tong',
      'Sambour',
      'Saen Dei',
      'Skuh',
      'Tang Krouch',
      'Thummoda Ar',
      'Trapeang Kong',
      'Tumpoar Meas',
      'Voa Sar',
    ],
    'Thpong': [
      'Amleang',
      'Monourom',
      'Prambei Mum',
      'Rung Roeang',
      'Toap Mean',
      'Veal Pon',
      'Yea Angk',
    ],
  },
  'Kampong Thom': {
    'Baray': [
      'Bak Sna',
      'Ballangk',
      'Baray',
      'Boeng',
      'Chaeung Daeung',
      'Chraneang',
      'Chhuk Khsach',
      'Chong Doung',
      'Chrolong',
      'Kokir Thum',
      'Krava',
      'Andoung Pou',
      'Pongro',
      'Sou Young',
      'Sralau',
      'Svay Phleung',
      'Tnaot Chum',
      'Triel',
    ],
    'Kampong Svay': [
      'Chey',
      'Damrei Slab',
      'Kampong Kou',
      'Kampong Svay',
      'Nipech',
      'Phat Sanday',
      'San Kor',
      'Tbaeng',
      'Trapeang Ruessei',
      'Kdei Doung',
      'Prey Kuy',
    ],
    'Stueng Saen Municipality': [
      'Damrei Choan Khla Sangkat',
      'Kampong Thum Sangkat',
      'Kampong Roteh Sangkat',
      'Ou Kanthor Sangkat',
      'Kampong Krabau Sangkat',
      'Prey Ta Hu Sangkat',
      'Achar Leak Sangkat',
      'Srayov Sangkat',
    ],
    'Prasat Ballangk': [
      'Doung',
      'Kraya',
      'Phan Nheum',
      'Sakream',
      'Sala Visai',
      'Sameakki',
      'Tuol Kreul',
    ],
    'Prasat Sambour': ['Chhuk', 'Koul', 'Sambour', 'Sraeung', 'Tang Krasau'],
    'Sandan': [
      'Chheu Teal',
      'Dang Kambet',
      'Klaeng',
      'Mean Rith',
      'Mean Chey',
      'Ngan',
      'Sandan',
      'Sochet',
      'Tum Ring',
    ],
    'Santuk': [
      'Boeng Lvea',
      'Chroab',
      'Kampong Thma',
      'Kakaoh',
      'Kraya',
      'Pnov',
      'Prasat',
      'Tang Krasang',
      'Ti Pou',
      'Tboung Krapeu',
    ],
    'Stoung': [
      'Banteay Stoung',
      'Chamna Kraom',
      'Chamna Leu',
      'Kampong Chen Cheung',
      'Kampong Chen Tboung',
      'Msa Krang',
      'Peam Bang',
      'Popok',
      'Pralay',
      'Preah Damrei',
      'Rung Roeang',
      'Samprouch',
      'Trea',
    ],
  },
  'Kampot': {
    'Angkor Chey': [
      'Angk Phnum Touch',
      'Ankor Chey',
      'Champei',
      'Dambouk Khpos',
      'Dan Koum',
      'Daeum Doung',
      'Mroum',
      'Phnum Kong',
      'Praphnum',
      'Samlanh',
      'Tani',
    ],
    'Banteay Meas': [
      'Banteay Meas Khang Kaeut',
      'Banteay Meas Khang lech',
      'Prey Tonle',
      'Samraong Kraom',
      'Samraong Leu',
      'Sdach Kong Khang Cheung',
      'Sdach Kong Khang lech',
      'Sdach Kong Khang Tboung',
      'Tnoat Chong Srang',
      'Trapeang Sala Khang Kaeut',
      'Trapeang Sala Khang Lech',
      'Tuk Meas Khang Kaeut',
      'Tuk Meas Khang Lech',
      'Voat Angk Khang Cheung',
      'Voat Angk Khang Tboung',
    ],
    'Chhuk': [
      'Baniev',
      'Takaen',
      'Boeng Nimol',
      'Chhuk',
      'Doun Yay',
      'Krang Sbov',
      'Krang Snay',
      'Lbaeuk',
      'Trapeang Phleang',
      'Mean Chey',
      'Neareay',
      'Satv Pong',
      'Trapeang Bei',
      'Tramaeng',
      'Dechou Akphivoadth',
    ],
    'Chum Kiri': [
      'Chres',
      'Chumpu Voan',
      'Snay Anhchit',
      'Srae Chaeng',
      'Srae Knong',
      'Srae Samraong',
      'Trapeang Reang',
    ],
    'Dang Tong': [
      'Damnak Sokram',
      'Dang Tong',
      'Khcheay Khang Cheung',
      'Khcheay Khang Tboung',
      'Mean Ritth',
      'Srae Chea Khang Cheung',
      'Srae Chea Khang Tboung',
      'Totung',
      'Angk Romeas',
      "L'ang",
    ],
    'Kampong Trach': [
      'Boeng Sala Khang Cheung',
      'Boeng Sala Khang Tboung',
      'Damnak Kantuot Khang Cheung',
      'Damnak Kantuot Khang Tboung',
      'Kampong Trach Khang Kaeut',
      'Kampong Trach Khang Lech',
      'Prasat Phnom Khyang',
      'Phnom Prasat',
      'Ang Sophy',
      'Preaek Kroes',
      'Ruessei Srok Khang Kaeut',
      'Ruessei Srok Khang Lech',
      'Svay Tong Khang Cheung',
      'Svay Tong Khang Tboung',
    ],
    'Tuek Chhou': [
      'Boeng Tuk',
      'Chum Kriel',
      'Kampong Kraeng',
      'Kampong Samraong',
      'Kandaol',
      'Kaoh Touch',
      'Koun Satv',
      'Makprang',
      'Preaek Tnoat',
      'Prey Khmum',
      'Prey Thnang',
      'Stueng Kaev',
      'Thmei',
      'Trapeang Pring',
      'Trapeang Sangkae',
      'Trapeang Thum',
    ],
    'Kampot Municipality': [
      'Kampong Kandal Sangkat',
      'Krang Ampil Sangkat',
      'Kampong Bay Sangkat',
      'Andoung Khmer Sangkat',
      'Traeuy Kaoh Sangkat',
    ],
  },
  'Kandal': {
    'Kandal Stueng': [
      'Ampov Prey',
      'Anlong Romiet',
      'Barku',
      'Boeng Khyang',
      'Cheung Kaeub',
      'Daeum Rues',
      'Kandaok',
      'Thmei',
      'Kouk Trab',
      'Preah Putth',
      'Preaek Roka',
      'Preaek Slaeng',
      'Roka',
      'Roleang Kaen',
      'Siem Reab',
      'Tbaeng',
      'Trapeang Veaeng',
      'Trea',
    ],
    'Kien Svay': [
      'Banteay Daek',
      'Chheu Teal',
      'Dei Edth',
      'Kampong Svay',
      'Kokir',
      'Kokir Thum',
      'Phum Thum',
      'Samraong Thum',
    ],
    'Khsach Kandal': [
      'Bak Dav',
      'Chey Thum',
      'Kampong Chamlang',
      'Kaoh Chouram',
      'Kaoh Oknha Tei',
      'Preah Prasab',
      'Preaek Ampil',
      'Preaek Luong',
      'Preaek Ta kov',
      'Preaek Ta Meak',
      'Puk Ruessei',
      'Roka Chonlueng',
      'Sanlung',
      'Sithor',
      'Svay Chrum',
      'Svay Romiet',
      'Ta Aek',
      'Vihear Suork',
    ],
    'Kaoh Thum': [
      'Chheu Kmau',
      'Chrouy Ta Kaev',
      'Kampong Kong',
      'Kaoh Thum Ka',
      'Kaoh Thum Kha',
      'Leuk Daek',
      'Pouthi Ban',
      'Preaek Chrey',
      'Preaek Sdei',
      'Preaek Thmei',
      'Sampeou Poun',
    ],
    'Leuk Daek': [
      'Kampong Phnum',
      "K'am Samnar",
      'Khpob Ateav',
      'Peam Reang',
      'Preaek Dach',
      'Preaek Tonloab',
      'Sandar',
    ],
    'Lvea Aem': [
      'Akreiy Ksatr',
      'Barong',
      'Boeng Krum',
      'Kaoh Kaev',
      'Kaoh Reah',
      'Lvea Sar',
      'Peam Oknha Ong',
      'Phum Thum',
      'Preaek Kmeng',
      'Preaek Rey',
      'Preaek Ruessei',
      'Sambuor',
      'Sarikakaev',
      'Thma Kor',
      'Tuek Khleang',
    ],
    'Mukh Kampul': [
      'Preaek Anhchanh',
      'Preaek Dambang',
      'Roka Kong Ti Muoy',
      'Roka Kong Ti Pir',
      'Ruessei Chrouy',
      'Sambuor Meas',
      'Svay Ampear',
    ],
    'Angk Snuol': [
      'Baek Chan',
      'Chhak Chheu Neang',
      'Damnak Ampil',
      'Krang Mkak',
      'Lumhach',
      'Mkak',
      'Peuk',
      'Prey Puoch',
      'Samraong Leu',
      'Tuol Prech',
    ],
    'Ponhea Lueu': [
      'Chhveang',
      'Chrey Loas',
      'Kampong Luong',
      'Kampong Os',
      'Kaoh Chen',
      'Phnum Bat',
      'Ponhea Lueu',
      'Preaek Ta Teaen',
      'Phsar Daek',
      'Tumnob Thum',
      'Vihear Luong',
    ],
    "S'ang": [
      'Khpob',
      'Kaoh Anlong Chen',
      'Kaoh Khael',
      'Kaoh Khsach Tonlea',
      'Krang Yov',
      'Prasat',
      'Preaek Ambel',
      'Preaek Koy',
      'Roka Khpos',
      "S'ang Phnum",
      'Setbou',
      'Svay Prateal',
      'Svay Rolum',
      'Ta Lon',
      'Traeuy Sla',
      'Tuek Vil',
    ],
    'Ta Khmau Municipality': [
      'Ta Kdol Sangkat',
      'Prek Ruessey Sangkat',
      'Doeum Mien Sangkat',
      'Ta Khmao Sangkat',
      'Prek Ho Sangkat',
      'Kampong Samnanh Sangkat',
    ],
  },
  'Kep': {
    "Damnak Chang'aeur": ['Angkaol', 'Pong Tuek'],
    'Kaeb Municipality': [
      'Kaeb Sangkat',
      'Prey Thum Sangkat',
      'Ou Krasar Sangkat',
    ],
  },
  'Koh Kong': {
    'Botum Sakor': ['Andoung Tuek', 'Kandaol', 'Ta Noun', 'Thma Sa'],
    'Kiri Sakor': ['Kaoh Sdach', 'Phnhi Meas', 'Preaek Khsach'],
    'Kaoh Kong': ['Chrouy Pras', 'Kaoh Kapi', 'Ta Tai Kraom', 'Trapeang Rung'],
    'Khemara Phoumin Municipality': [
      'Smach Mean Chey Sangkat',
      'Dang Tong Sangkat',
      'Stueng Veaeng Sangkat',
    ],
    'Mondol Seima': ['Pak Khlang', 'Peam Krasaob', 'Tuol Kokir'],
    'Srae Ambel': [
      'Boeng Preav',
      'Chi Kha Kraom',
      'Chi kha Leu',
      'Chrouy Svay',
      'Dang Peaeng',
      'Srae Ambel',
    ],
    'Thma Bang': [
      'Ta Tey Leu',
      'Pralay',
      'Chumnoab',
      'Ruessei Chrum',
      'Chi Phat',
      'Thma Doun Pov',
    ],
  },
  'Kratie': {
    'Chhloung': [
      'Chhloung',
      'Damrei Phong',
      'Han Chey',
      'Kampong Damrei',
      'Kanhchor',
      'Khsach Andeth',
      'Pongro',
      'Preaek Saman',
    ],
    'Kracheh Municipality': [
      'Kaoh Trong Sangkat',
      'Krakor Sangkat',
      'Kracheh Sangkat',
      'Ou Ruessei Sangkat',
      'Roka Kandal Sangkat',
    ],
    'Prek Prasab': [
      'Chambâk',
      'Chrouy Banteay',
      'Kampong Kor',
      'Koh Ta Suy',
      'Preaek Prasab',
      'Russey Keo',
      'Saob',
      'Ta Mao',
    ],
    'Sambour': [
      'Boeng Char',
      'Kampong Cham',
      'Kbal Damrei',
      'Kaoh Khnhaer',
      'Ou Krieng',
      'Roluos Mean Chey',
      'Sambour',
      'Sandan',
      'Srae Chis',
      'Voadthonak',
    ],
    'Snuol': [
      'Khsuem',
      'Pir Thnu',
      'Snuol',
      'Srae Char',
      'Svay Chreah',
      'Kronhoung Saen Chey',
    ],
    'Chetr Borei': [
      'Bos Leav',
      'Changkrang',
      'Dar',
      'Kantuot',
      'Kou Loab',
      'Kaoh Chraeng',
      'Sambok',
      'Thma Andaeuk',
      'Thma Kreae',
      'Thmei',
    ],
  },
  'Mondulkiri': {
    'Kaev Seima': [
      'Chong Phlah',
      'Memang',
      'Srae Chhuk',
      'Srae Khtum',
      'Srae Preah',
    ],
    'Kaoh Nheaek': [
      'Nang Khi Lik',
      'A Buon Leu',
      'Roya',
      'Sokh Sant',
      'Srae Huy',
      'Srae Sangkum',
    ],
    'Ou Reang': ['Dak Dam', 'Saen Monourom'],
    'Pech Chreada': ['Krang Teh', 'Pu Chrey', 'Srae Ampum', 'Bu Sra'],
    'Saen Monourom Municipality': [
      'Monourom Sangkat',
      'Sokh Dom Sangkat',
      'Spean Mean Chey Sangkat',
      'Romonea Sangkat',
    ],
  },
  'Oddar Meanchey': {
    'Anlong Veaeng': [
      'Anlong Veaeng',
      'Trapeang Tav',
      'Trapeang Prei',
      'Thlat',
      'Lumtong',
    ],
    'Banteay Ampil': ['Ampil', 'Beng', 'Kouk Khpos', 'Kouk Mon'],
    'Chong Kal': ['Cheung Tien', 'Chong Kal', 'Krasang', 'Pongro'],
    'Samraong Municipality': [
      'Bansay Reak Sangkat',
      'Bos Sbov Sangkat',
      'Koun Kriel Sangkat',
      'Samraong Sangkat',
      'Ou Smach Sangkat',
    ],
    'Trapeang Prasat': [
      'Bak Anloung',
      "Ph'av",
      'Ou Svay',
      'Preah Pralay',
      'Tumnob Dach',
      'Trapeang Prasat',
    ],
  },
  'Pailin': {
    'Pailin Municipality': [
      'Pailin Sangkat',
      'Ou Ta Vau Sangkat',
      'Tuol Lvea Sangkat',
      'Bar Yakha Sangkat',
    ],
    'Sala Krau': ['Sala Krau', 'Stueng Trang', 'Stueng Kach', 'Ou Andoung'],
  },
  'Preah Sihanouk': {
    'Preah Sihanouk Municipality': [
      'lek Muoy Sangkat',
      'Pir Sangkat',
      'Bei Sangkat',
      'Buon Sangkat',
      'Kaoh Rung Sangkat',
      'Koah Rung Sonlem Sangkat',
    ],
    'Prey Nob': [
      'Andoung Thma',
      'Boeng Ta Prum',
      'Bet Trang',
      'Cheung Kou',
      'Ou Chrov',
      'Ou Oknha Heng',
      'Prey Nob',
      'Ream',
      'Sameakki',
      'Samrong',
      "Tuek L'ak",
      'Tuek Thla',
      'Tuol Totueng',
      'Veal Renh',
      'Ta Ney',
    ],
    'Stueng Hav': ['Kampenh', 'Ou Treh', 'Tumnob Rolok', 'Kaev Phos'],
    'Kampong Seila': [
      'Chamkar Luong',
      'Kampong Seila',
      'Ou Bak Roteh',
      'Stueng Chhay',
    ],
  },
  'Preah Vihear': {
    'Chey Saen': ["S'ang", 'Tasu', 'Khyang', 'Chrach', 'Thmea', 'Putrea'],
    'Chhaeb': [
      'Chhaeb Muoy',
      'Chhaeb Pir',
      'Sangkae Muoy',
      'Sangkae Pir',
      'Mlu Prey Muoy',
      'Mlu Prey Pir',
      'Kampong Sralau Muoy',
      'Kampong Sralau Pir',
    ],
    'Choam Ksant': [
      'Choam Ksant',
      'Tuek Kraham',
      'Pring Thum',
      'Rumdaoh Srae',
      'Yeang',
      'Kantuot',
      'Sror Aem',
      'Morokot',
    ],
    'Kuleaen': [
      'Kuleaen Tboung',
      'Kuleaen Cheung',
      'Thmei',
      'Phnum Penh',
      'Phnum Tbaeng Pir',
      'Srayang',
    ],
    'Rovieng': [
      'Robieb',
      'Reaksmei',
      'Rohas',
      'Rung Roeang',
      'Rik Reay',
      'Ruos Roan',
      'Rotanak',
      'Rieb Roy',
      'Reaksa',
      'Rumdaoh',
      'Romtum',
      'Romoneiy',
    ],
    'Sangkum Thmei': [
      'Chamraeun',
      "Ro'ang",
      'Phnum Tbaeng Muoy',
      'Sdau',
      'Ronak Ser',
    ],
    'Tbaeng Mean Chey': ['Chhean Mukh', 'Pou', 'Prame', 'Preah Khleang'],
    'Preah Vihear Municipality': ['Kampong Pranak Sangkat', 'Pal Hal Sangkat'],
  },
  'Prey Veng': {
    'Ba Phnum': [
      'Boeng Preah',
      'Cheung Phnum',
      'Chheu Kach',
      'Reaks Chey',
      'Roung Damrei',
      'Sdau Kaong',
      'Spueu Ka',
      'Spueu Kha',
      'Theay',
    ],
    'Kamchay Mear': [
      'Cheach',
      'Doun Koeng',
      'Kranhung',
      'Krabau',
      'Seang Khveang',
      'Smaong Khang Cheung',
      'Smaong Khang Tboung',
      'Trabaek',
    ],
    'Kampong Trabaek': [
      'Ansaong',
      'Cham',
      'Cheang Daek',
      'Chrey',
      'Kansoam Ak',
      'Kou Khchak',
      'Kampong Trabaek',
      'Peam Montear',
      'Prasat',
      'Pratheat',
      'Prey Chhor',
      'Prey Poun',
      'Thkov',
    ],
    'Kanhchriech': [
      'Chong Ampil',
      'Kanhchriech',
      'Kdoeang Reay',
      'Kouk Kong Kaeut',
      'Kouk Kong Lech',
      'Preal',
      'Thma Pun',
      'Tnaot',
    ],
    'Me Sang': [
      'Angkor Sar',
      'Chres',
      'Chi Phoch',
      'Prey Khnes',
      'Prey Rumdeng',
      'Prey Totueng',
      'Svay Chrum',
      'Trapeang Srae',
    ],
    'Peam Chor': [
      'Angkor Angk',
      'Kampong Prasat',
      'Kaoh Chek',
      'Kaoh Roka',
      'Kaoh Sampov',
      'Krang Ta Yang',
      'Preaek Krabau',
      'Preaek Sambuor',
      'Ruessei Srok',
      'Svay Phluoh',
    ],
    'Peam Ro': [
      'Ba Baong',
      'Banlich Prasat',
      'Neak Loeang',
      'Peam Mean Chey',
      'Peam Ro',
      'Preaek Khsay Ka',
      'Preaek Khsay Kha',
      'Prey Kandieng',
    ],
    'Pea Reang': [
      'Kampong Popil',
      'Kanhcham',
      'Kampong Prang',
      'Mesar Prachan',
      'Prey Pnov',
      'Prey Sniet',
      'Prey Sralet',
      'Reab',
      'Roka',
    ],
    'Preah Sdach': [
      'Angkor Reach',
      'Banteay Chakrei',
      'Boeng Daol',
      'Chey Kampok',
      'Kampong Soeng',
      'Krang Svay',
      'Lvea',
      'Preah Sdach',
      'Reathor',
      'Rumchek',
      'Sena Reach Otdam',
    ],
    'Prey Veng Municipality': [
      'Baray Sangkat',
      'Cheung Tuek Sangkat',
      'Kampong Leav Sangkat',
    ],
    'Pur Rieng': [
      'Pou Rieng',
      'Preaek Anteah',
      'Preaek Chrey',
      'Prey Kanlaong',
      'Ta Kao',
      'Kampong Ruessei',
      'Preaek Ta Sar',
    ],
    'Sithor Kandal': [
      'Ampil Krau',
      'Chrey Khmum',
      'Lve',
      'Pnov Ti Muoy',
      'Pnov Ti Pir',
      'Pou Ti',
      'Preaek Changkran',
      'Prey Daeum Thnoeng',
      'Prey Tueng',
      'Rumlech',
      'Ruessei Sanh',
    ],
    'Svay Antor': [
      'Angkor Tret',
      'Chea Khlang',
      'Chrey',
      'Damrei Puon',
      'Me Bon',
      'Pean Roung',
      'Popueus',
      'Prey Khla',
      'Samraong',
      'Svay Antor',
      'Tuek Thla',
    ],
  },
  'Pursat': {
    'Bakan': [
      'Boeng Bat Kandaol',
      'Boeng Khnar',
      'Khnar Totueng',
      'Me Tuek',
      'Ou Ta Paong',
      'Rumlech',
      'Snam Preah',
      'Svay Doun Kaev',
      'Ta Lou',
      'Trapeang chorng',
    ],
    'Kandieng': [
      'Anlong Vil',
      'Kandieng',
      'Kanhchor',
      'Reang Til',
      'Srae Sdok',
      'Svay Luong',
      'Sya',
      'Veal',
      'Kaoh Chum',
    ],
    'Krakor': [
      'Anlong Tnaot',
      'Ansa Chambak',
      'Boeng Kantuot',
      'Chheu Tom',
      'Kampong Luong',
      'Kampong Pou',
      'Kbal Trach',
      'Ou Sandan',
      'Sna Ansa',
      'Svay Sa',
      'Tnaot Chum',
    ],
    'Phnum Kravanh': [
      'Bak Chenhchien',
      'Leach',
      'Phteah Rung',
      'Prongil',
      'Rokat',
      'Santreae',
      'Samraong',
    ],
    'Pursat Municipality': [
      'Chamraeun Phal Sangkat',
      'Lolok Sa Sangkat',
      'Phteah Prey Sangkat',
      'Prey Nhi Sangkat',
      'Roleab Sangkat',
      'Svay At Sangkat',
      'Banteay Dei Sangkat',
    ],
    'Veal Veaeng': [
      'Ou Saom',
      'Krapeu Pir',
      'Anlong Reab',
      'Pramaoy',
      'Thma Da',
    ],
  },
  'Ratanakiri': {
    'Andoung Meas': ['Malik', 'Nhang', 'Ta Lav'],
    'Ban Lung Municipality': [
      'Kachanh Sangkat',
      'Labansiek Sangkat',
      'Yeak Laom Sangkat',
      'Boeng Kansaeng Sangkat',
    ],
    'Bar Kaev': [
      'Kak',
      'Keh Chong',
      'La Minh',
      'Lung Khung',
      'Saeung',
      'Ting Chak',
    ],
    'Koun Mom': [
      'Serei Mongkol',
      'Srae Angkrorng',
      'Ta Ang',
      'Teun',
      'Trapeang Chres',
      'Trapeang Kraham',
    ],
    'Lumphat': [
      'Chey Otdam',
      'Ka Laeng',
      'Lbang Muoy',
      'Lbang Pir',
      'Ba Tang',
      'Seda',
    ],
    'Ou Chum': [
      'Cha Ung',
      'Pouy',
      'Aekakpheap',
      'Kalai',
      'Ou Chum',
      'Sameakki',
      "L'ak",
    ],
    'Ou Ya Dav': [
      'Bar Kham',
      'Lum Choar',
      'Pak Nhai',
      'Pa Te',
      'Sesan',
      'Saom Thum',
      'Ya Tung',
    ],
    'Ta Veaeng': ['Ta Veaeng Leu', 'Ta Veaeng Kraom'],
    'Veun Sai': [
      'Pong',
      'Hat Pak',
      'Ka Choun',
      'Kaoh Pang',
      'Kaoh Peak',
      'Kok Lak',
      'Pa Kalan',
      'Phnum Kok',
      'Veun Sai',
    ],
  },
  'Siem Reap': {
    'Angkor Chum': [
      'Char Chhuk',
      'Doun Peng',
      'Kouk Doung',
      'Koul',
      'Nokor Pheas',
      'Srae Khvav',
      'Ta Saom',
    ],
    'Angkor Thum': ['Chob Ta Trav', 'Leang Dai', 'Peak Snaeng', 'Svay Chek'],
    'Banteay Srei': [
      'Khnar Sanday',
      'Khun Ream',
      'Preah Dak',
      'Rumchek',
      'Run Ta Aek',
      'Tbaeng',
    ],
    'Chi Kraeng': [
      'Anlong Samnar',
      'Chi Kraeng',
      'Kampong Kdei',
      'Khvav',
      'Kouk Thlok Kraom',
      'Kouk Thlok Leu',
      'Lveaeng Ruessei',
      'Pongro Kraom',
      'Pongro Leu',
      'Ruessei Lok',
      'Sangvaeuy',
      'Spean Tnaot',
    ],
    'Kralanh': [
      'Chanleas Dai',
      'Kampong Thkov',
      'Kralanh',
      'Krouch Kor',
      'Roung Kou',
      'Sambuor',
      'Saen Sokh',
      'Snuol',
      'Sranal',
      'Ta An',
    ],
    'Puok': [
      'Sasar Sdam',
      'Doun Kaev',
      'Kdei Run',
      'Kaev Poar',
      'Khnat',
      'Lvea',
      'Mukh Paen',
      'Pou Treay',
      'Puok',
      'Prey Chruk',
      'Reul',
      'Samraong Yea',
      'Trei Nhoar',
      'Yeang',
    ],
    'Prasat Bakong': [
      'Bakong',
      'Ballangk',
      'Kampong Phluk',
      'Kantreang',
      'Kandaek',
      'Mean Chey',
      'Roluos',
      'Trapeang Thum',
      'Ampil Sangkat',
    ],
    'Siem Reap Municipality': [
      'Sla Kram Sangkat',
      'Svay Dankum Sangkat',
      'Kok Chak Sangkat',
      'Sala Kamreuk Sangkat',
      'Nokor Thum Sangkat',
      'Chreav Sangkat',
      'Chong Khnies Sangkat',
      'Sngkat Sambuor Sangkat',
      'Siem Reab Sangkat',
      'Srangae Sangkat',
      'Krabei Riel Sangkat',
      'Tuek Vil Sangkat',
    ],
    'Soutr Nikom': [
      'Chan Sa',
      'Dam Daek',
      'Dan Run',
      'Kampong Khleang',
      'Kien Sangkae',
      'Khchas',
      'Khnar Pou',
      'Popel',
      'Samraong',
      'Ta Yaek',
    ],
    'Srei Snam': [
      'Chrouy Neang Nguon',
      'Klang Hay',
      'Tram Sasar',
      'Moung',
      'Prei',
      'Slaeng Spean',
    ],
    'Svay Leu': [
      'Boeng Mealea',
      'Kantuot',
      'Khnang Phnum',
      'Svay Leu',
      'Ta Siem',
    ],
    'Varin': ['Prasat', 'Lvea Krang', 'Srae Nouy', 'Svay Sa', 'Varin'],
  },
  'Stung Treng': {
    'Sesan': [
      'Kamphun',
      'Kbal Romeas',
      'Phluk',
      'Samkhuoy',
      'Sdau',
      'Srae Kor',
      'Ta Lat',
    ],
    'Siem Bouk': [
      'Kaoh Preah',
      'Kaoh Sampeay',
      'Kaoh Sralay',
      'Ou Mreah',
      'Ou Ruessei Kandal',
      'Siem Bouk',
      'Srae Krasang',
    ],
    'Siem Pang': [
      'Preaek Meas',
      'Sekong',
      'Santepheap',
      'Srae Sambour',
      'Tma Kaev',
    ],
    'Stueng Traeng Municipality': [
      'Stueng Traeng Sangkat',
      'Srah Ruessei Sangkat',
      'Preah Bat Sangkat',
      'Sameakki Sangkat',
    ],
    'Thala Barivat': [
      'Anlong Phe',
      'Chamkar Leu',
      'Kang Cham',
      'Kaoh Snaeng',
      'Anlong Chrey',
      'Ou Rai',
      'Ou Svay',
      'Preah Rumkel',
      'Sam Ang',
      'Srae Ruessei',
      'Thala Barivat',
    ],
  },
  'Svay Rieng': {
    'Chantrea': [
      'Chantrea',
      'Chres',
      'Me Sar Thngak',
      'Prey Kokir',
      'Samraong',
      'Tuol Sdei',
    ],
    'Kampong Rou': [
      'Banteay Krang',
      'Nhor',
      'Khsaetr',
      'Preah Ponlea',
      'Prey Thum',
      'Reach Montir',
      'Samlei',
      'Samyaong',
      'Svay Ta Yean',
      'Thmei',
      'Tnaot',
    ],
    'Rumduol': [
      'Bos Mon',
      'Thmea',
      'Kampong Chak',
      'Chrung Popel',
      'Kampong Ampil',
      'Meun Chey',
      'Pong Tuek',
      'Sangkae',
      'Svay Chek',
      'Thna Thnong',
    ],
    'Romeas Haek': [
      'Ampil',
      'Andoung Pou',
      'Andoung Trabaek',
      'Angk Prasrae',
      'Chantrei',
      'Chrey Thum',
      'Doung',
      'Kampong Trach',
      'Kokir',
      'Krasang',
      'Mukh Da',
      'Mream',
      'Sambuor',
      'Sambatt Mean Chey',
      'Trapeang Sdau',
      'Tras',
    ],
    'Svay Chrum': [
      'Angk Ta Sou',
      'Basak',
      'Chambak',
      'Kampong Chamlang',
      'Ta Suos',
      'Chheu Teal',
      'Doun Sa',
      'Kouk Pring',
      'Kraol Kou',
      'Kruos',
      'Pouthi Reach',
      'Svay Angk',
      'Svay Chrum',
      'Svay Thum',
      'Svay Yea',
      'Thlok',
    ],
    'Svay Rieng Municipality': [
      'Svay Rieng Sangkat',
      'Prey Chhlak Sangkat',
      'Koy Trabaek Sangkat',
      'Pou Ta Hao Sangkat',
      'Chek Sangkat',
      'Svay Toea Sangkat',
      'Sangkhoar Sangkat',
    ],
    'Svay Teab': [
      'Koki Saom',
      'Kandieng Reay',
      'Monourom',
      'Popeaet',
      'Prey Ta Ei',
      'Prasoutr',
      'Romeang Thkaol',
      'Sambuor',
      'Svay Rumpear',
    ],
    'Bavet Municipality': [
      'Bati Sangkat',
      'Bavet Sangkat',
      'Chrak Mtes Sangkat',
      'Prasat Sangkat',
      'Prey Angkunh Sangkat',
    ],
  },
  'Takeo': {
    'Angkor Borei': [
      'Angkor Borei',
      'Ba Srae',
      'Kouk Thlok',
      'Ponley',
      'Preaek Phtoul',
      'Prey Phkoam',
    ],
    'Bati': [
      'Chambak',
      'Champei',
      'Doung',
      'Kandoeng',
      'Komar Reachea',
      'Krang Leav',
      'Krang Thnong',
      'Lumpong',
      'Pea Ream',
      'Pot Sar',
      'Sour Phi',
      'Tang Doung',
      'Tnaot',
      'Trapeang Krasang',
      'Trapeang Sab',
    ],
    'Borei Cholsar': [
      'Borei Cholsar',
      'Chey Chouk',
      'Doung Khpos',
      'Kampong Krasang',
      'Kouk Pou',
    ],
    'Kiri Vong': [
      'Angk Prasat',
      'Preah Bat Choan Chum',
      'Kamnab',
      'Kampeaeng',
      'Kiri Chong Kaoh',
      'Kouk Prech',
      'Phnum Den',
      'Prey Ampok',
      'Prey Rumdeng',
      'Ream Andaeuk',
      'Saom',
      'Ta Ou',
    ],
    'Kaoh Andaet': [
      'Krapum Chhuk',
      'Pech Sar',
      'Prey Khla',
      'Prey Yuthka',
      'Romenh',
      'Thlea Prachum',
    ],
    'Prey Kabbas': [
      'Angkanh',
      'Ban Kam',
      'Champa',
      'Char',
      'Kampeaeng',
      'Kampong Reab',
      'Kdanh',
      'Pou Rumchak',
      'Prey Kabbas',
      'Prey Lvea',
      'Prey Phdau',
      'Snao',
      'Tang Yab',
    ],
    'Samraong': [
      'Boeng Tranh Khang Cheung',
      'Boeng Tranh Khang Tboung',
      'Cheung Kuon',
      'Chumreah Pen',
      'Khvav',
      'Lumchang',
      'Rovieng',
      'Samraong',
      'Soengh',
      'Sla',
      'Trea',
    ],
    'Doun Kaev Municipality': [
      'Baray Sangkat',
      'Roka Knong Sangkat',
      'Roka Krau Sangkat',
    ],
    'Tram Kak': [
      'Angk Ta Saom',
      'Cheang Tong',
      'Kus',
      'Leay Bour',
      'Nhaeng Nhang',
      'Ou Saray',
      'Trapeang Kranhoung',
      'Otdam Soriya',
      'Popel',
      'Samraong',
      'Srae Ronoung',
      'Ta Phem',
      'Tram Kak',
      'Trapeang Thum Khang Cheung',
      'Trapeang Thum Khang Tboung',
    ],
    'Treang': [
      'Angkanh',
      'Angk Khnor',
      'Chi Khma',
      'Khvav',
      'Prambei Mum',
      'Angk Kaev',
      'Prey Sloek',
      'Roneam',
      'Sambuor',
      'Sanlung',
      'Smaong',
      'Srangae',
      'Thlok',
      'Tralach',
    ],
  },
  'Tboung Khmum': {
    'Dambae': [
      'Chong Cheach',
      'Dambae',
      'Kouk Srok',
      'Neang Teut',
      'Seda',
      'Trapeang Pring',
      'Tuek Chrov',
    ],
    'Krouch Chhmar': [
      'Chhuk',
      'Chumnik',
      'Kampong Treas',
      'Kaoh Pir',
      'Krouch Chhmar',
      'Peus Muoy',
      'Peus Pir',
      'Preaek A chi',
      'Roka Khnor',
      'Svay Khleang',
      'Trea',
      'Tuol Snuol',
    ],
    'Memot': [
      'Chan Mul',
      'Choam',
      'Choam Kravien',
      'Choam Ta Mau',
      'Dar',
      'Kampoan',
      'Kokir',
      'Memong',
      'Memot',
      'Rumchek',
      'Rung',
      'Tonlung',
      'Tramung',
      'Triek',
    ],
    'Ou Reang Ov': [
      'Ampil Ta Pok',
      'Chak',
      'Damril',
      'Kong Chey',
      'Mien',
      'Preah Theat',
      'Tuol Souphi',
    ],
    'Ponhea Kraek': [
      'Dountei',
      'Kak',
      'Kandaol Chrum',
      'Kaong Kang',
      'Kraek',
      'Popel',
      'Trapeang Phlong',
      'Veal Mlu',
    ],
    'Suong Municipality': ['Suong Sangkat', 'Vihear Luong Sangkat'],
    'Tboung Khmum': [
      'Anhchaeum',
      'Boeng Pruol',
      'Chikor',
      'Chirou Ti Muoy',
      'Chirou Ti Pir',
      'Chob',
      'Kor',
      'Lngieng',
      'Mong Riev',
      'Peam Chileang',
      'Roka Po Pram',
      'Sralab',
      'Thma Pech',
      'Tonle Bet',
    ],
  },
};
